INSERT INTO Products (Id, BrandId, ProductName, Description, CostPrice, MSRP, QtyOnHand, QtyOnBackOrder, GraphicName)
VALUES
(NEWID(), 1, 
'Kingdom Hearts HD 2.8 Final Chapter Prologue', 'Kingdom Hearts HD 2.8 Final Chapter Prologue includes a high-definition remaster of Kingdom Hearts 3D: Dream Drop Distance, as well as two new pieces of content to the Kingdom Hearts series. The first, Kingdom Hearts Back Cover, is a cinematic based on Kingdom Hearts that details events not shown in the original game. The other, Kingdom Hearts 0.2: Birth by Sleep – A Fragmentary Passage, is an original game that takes place after the events of Dream Drop Distance, with a majority of the story taking place after the events of Birth by Sleep and during the events of Kingdom Hearts, from the perspective of Aqua.',
30.00, 49.99, 10, 8, 'kingdomhearts2.8.jpg'),
(NEWID(),1,
'Kingdom Hearts HD 1.5 + 2.5 ReMIX', 'KINGDOM HEARTS HD 1.5 + 2.5 ReMIX is a compliation of six magical KINGDOM HEARTS experiences. See how Soras adventure and the Dark Seeker Saga against Xehanort begins!',
50.00, 64.99, 12, 14, 'kingdomhearts1.52.5.jpg'),
(NEWID(), 1,
'Bloodborne', 'Bloodborne is an action role-playing video game developed by FromSoftware and published by Sony Computer Entertainment for PlayStation 4. Bloodborne follows the player character, the Hunter, through the decrepit Gothic, Victorian era inspired city of Yharnam, whose inhabitants have been afflicted with an abnormal blood-borne disease. Upon mysteriously awakening in Yharnam during the night of The Hunt, the Hunter seeks out something known only as Paleblood for reasons unknown. The Hunter begins to unravel Yharnams intriguing mysteries while hunting down its many terrifying beasts. Eventually, the Hunters objective is to locate and terminate the source of the plague, and escape the nightmare.',
50.00, 69.99, 20, 5, 'bloodborne.jpg'),
(NEWID(), 1,
'The Last Gaurdian', 'The Last Guardian is an action-adventure video game developed by SIE Japan Studio and published by Sony Interactive Entertainment for the PlayStation 4 in December 2016. In The Last Guardian, players control a boy who befriends a giant half-bird-half-mammal creature, Trico.',
30.00, 49.99, 15, 10, 'gaurdian.jpg'),
(NEWID(), 1,
'Uncharted 4: A Thiefs End', 'A Thiefs End follows series protagonist Nathan Drake (portrayed by Nolan North), who has retired from fortune hunting several years after the events of Drakes Deception. He reunites with his estranged older brother Sam and longtime partner Sully to search for clues to the location of Captain Henry Averys long-lost treasure to save his brother.',
40.00, 59.99, 21, 10, 'uncharted.jpg'),
(NEWID(), 1,
'Destiny', 'Everything changed with the arrival of the Traveler. It sparked a Golden Age when our civilization spanned our solar system, but it did not last. Something hit us, knocked us down. The survivors built a city beneath the Traveler, and have begun to explore our old worlds, only to find them filled with deadly foes. You are a Guardian of the last safe city on Earth, able to wield incredible power. Defend the City. Defeat our enemies. Reclaim all that we have lost.',
60.00, 79.99, 11, 4, 'destiny.jpg'),
(NEWID(), 1,
'Assassins Creed Syndicate', 'The plot is set in a fictional history of real-world events and follows the centuries-old struggle between the Assassins, who fight for peace with liberty, and the Templars, who desire peace through order. The story is set in Victorian era London and follows twin assassins Jacob and Evie Frye as they navigate the corridors of organized crime, and take back the city from Templar control. The open world design lets players freely roam London.',
70.00, 89.99, 16, 4, 'syndicate.jpg'),
(NEWID(), 1,
'Fallout 4', 'Fallout 4 is set within an open world post-apocalyptic environment that encompasses the city of Boston and the surrounding Massachusetts region known as The Commonwealth. The main story takes place in the year 2287, ten years after the events of Fallout 3 and 210 years after The Great War, which caused catastrophic nuclear devastation across the United States.',
70.00, 89.99, 10, 13, 'fallout4.jpg'),
(NEWID(), 1,
'Final Fantasy XV', 'Final Fantasy XV takes place on the fictional world of Eos. All the worlds countries, bar the kingdom of Lucis, are under the dominion of the empire of Niflheim. Noctis Lucis Caelum, heir to the Lucian throne, goes on a quest to retake his homeland and its magical Crystal after it is seized by Niflheim on the eve of peace negotiations between the two nations. However, he soon discovers that the Crystal is at the heart of a much greater threat to Eos, and that his role as the future king is key to averting an apocalyptic event from taking place.',
60.00, 79.99, 24, 6, 'finalfantasy.jpg'),
(NEWID(), 1,
'Watch Dogs 2', 'Set within a fictionalized version of the San Francisco Bay Area, the game is played from a third-person perspective and its open world is navigated on-foot or by vehicle. Players control Marcus Holloway, a hacker who works with the hacking group DedSec to take down the citys advanced surveillance system known as ctOS. There are multiple ways to complete missions, and each successful assignment increases the follower count of DedSec.',
40.00, 59.99, 11, 10, 'watchdogs2.jpg'),
(NEWID(), 2,
'Gears of War 4', 'Gears of War 4 takes place 25 years after the Imulsion Countermeasure weapon destroyed all Imulsion on the planet Sera, taking the Locust and the Lambent with them as well. Unfortunately, this also knocked out the use of fossil fuels, forcing humanity to adapt new ways for survival. The countermeasure also brought the advent of Windflares, powerful windstorms that form across the planet. Following the aftermath of the Lambent Epidemic, the reformed Coalition of Ordered Governments estimated that only hundreds of thousands of humans are left on Sera. To prevent the population from declining, walled-off cities were built to protect the citizens from the dangers outside. The COG also declared martial law, preventing any travel from outside of city walls. Some human survivors rejected the viewpoints of the COG and formed a group called the Outsiders that live outside of the COG jurisdiction, conducting raids on COG territory to gather resources. The game focuses on the son of Marcus Fenix and Anya Stroud, J.D. Fenix, who, alongside his friends Delmont Del Walker and Kait Diaz deal with a new threat to humanitys survival.',
50.00, 69.99, 10, 12, 'gearsofwar.jpg'),
(NEWID(), 2,
'Halo 5: Guardians', 'A mysterious and unstoppable force threatens the galaxy, the Master Chief is missing and his loyalty questioned. Experience the most dramatic Halo story to date in a 4-player cooperative epic that spans three worlds. Challenge friends and rivals in new multiplayer modes: Warzone, massive 24-player battles, and Arena, pure 4-vs-4 competitive combat',
70.00, 89.99, 15, 9, 'halo5.jpg'),
(NEWID(), 2,
'Sunset Overdrive', 'Dive into the open-world shooter of Sunset Overdrive, and prove that you have got what it takes to survive catastrophe. With a knack for traversing the ruined city with hyper agility, it is a simple matter to survive postapocalyptic conditions. When it comes to the mutants, not only are you escaping their transformation, but you have found your true calling — mutant destroyer. A fully loaded arsenal of overpowered weapons back you up and make it totally clear that the end of days is just the beginning for you. It is your turn to star in this end-of-the-world storyline.',
30.00, 49.99, 24, 10, 'sunsetoverdrive.jpg'),
(NEWID(), 2,
'Forza Motorsport 6', 'Unrelenting action at simulation speed in the most beautiful and comprehensive racing game of this generation. Collect, customize, and race over 450 Forzavista cars, all with working cockpits and full damage. Compete in epic 24-player races across 26 world-famous locales. Master wet weather and night racing on your road to victory.',
40.00, 59.99, 34, 3, 'forza6.jpg'),
(NEWID(), 2,
'FIFA 17', 'Innovates across the entire pitch to deliver a balanced, authentic, and exciting football experience that lets you play your way, and compete at a higher level. And with all new ways to play! Set up the perfect goal in FIFA 17. New active intelligence let players learn even on the field and react to the ever-changing world around them, whether it is pouring down with rain or the opposition are unusually physical. Complete control gives you the opportunity to define your playing style in FIFA 2017.',
20.00, 39.99, 10, 13, 'fifa17.jpg'),
(NEWID(), 2,
'Batman: Arkham Knight', 'The finale to the legendary Arkham series explodes onto your screen in the most adrenaline-pumping storyline yet. The Scarecrow has returned to Gotham City and he has united a terrifying team of super villains, including Penguin, Two-Face and Harley Quinn. For the first time in the franchise, you get to step behind the wheel of the iconic Batmobile as you harness the power of Batman and scramble to outwit the wicked gang after your blood. Tear through the streets and soar across the skyline in heart-pounding gameplay that will suck you in and force you to ask yourself if you have what it takes to save Gotham. Do you have it within you to be the hero the city needs? Or will the villains of Gotham overtake the Dark Knight once and for all?',
40.00, 59.99, 7, 15, 'arkhamknight.jpg'),
(NEWID(), 2,
'Battlefield 1', 'Fight your way through numerous cities in Battlefield 1 for Xbox One. The deluxe edition includes the Red Baron, Lawrence of Arabia and Hellfighter packs, which contain themed weapons and customizable vehicles. Fight epic battles alongside 63 other online players, or battle in besieged cities, through country woodlands or over mountains in Battlefield 1 for Xbox One.',
10.00, 29.99, 9, 11, 'battlefield1.jpg'),
(NEWID(), 2,
'The Witcher 3: Wild Hunt', 'Experience action and adventure on an epic scale with The Witcher 3: Wild Hunt for Xbox One. This game includes two expansion packs, Hearts of Stone and Blood and Wine, for hours and hours of added game play. The Witcher 3 is packed with open-world RPG action to get your blood pumping.',
30.00, 49.99, 9, 10, 'witcher3.jpg'),
(NEWID(), 2,
'Mass Effect: Andromeda', 'Defeat dominant defenders of alien worlds in Mass Effect: Andromeda Deluxe for the Xbox One. Special Scavenger armor and a Pathfinder Elite weaponry set help you pulverize powerful opponents to protect humanity. Establish humanitys well-deserved place in the galaxy alone or with a group of friends in Mass Effect: Andromeda',
40.00, 59.99, 7, 13, 'andromeda.jpg'),
(NEWID(), 2,
'Titanfall 2', 'Be the hero in Respawn Entertainments Titanfall 2 Deluxe for Xbox One. The studio that created the original Titanfall has delivered a sequel challenging you to figure out whether you are willing to die for what you believe in. Live the adventure with Titanfall 2 Deluxe, and enjoy marathon gaming sessions whether playing alone or with friends.',
60.00, 79.99, 11, 16, 'titanfall2.jpg'),
(NEWID(), 3,
'Super Smash Bros.', 'Return to an exciting world of epic battles with Super Smash Bros. as you fight your way through a host of fan-favorite opponents. Journey through striking stages inspired by the most popular classic Nintendo games. Challenge a host of familiar faces to battle, including Mario, Link, Samus and Pikachu, or take on new contenders, such as Mega Man, Little Mac and Palutena, the Goddess of Light from the Kid Icarus games. Leap into battle as your own personalized Mii characters.',
40.00, 59.99, 10, 10, 'smashbros.jpg'),
(NEWID(), 3,
'Mario Kart 8', 'Feel the rush as your kart rockets across the ceiling! Race upside-down and along walls on anti-gravity tracks in the most action-fueled Mario Kart game yet! Take on racers across the globe and share videos of your greatest moments via Mario Kart TV.',
50.00, 69.99, 7, 18, 'mariokart8wiiu.jpg'),
(NEWID(), 3,
'Splatoon', 'Get messy with Splatoon, a fun-filled third-person action shooter that challenges you to cover levels, and enemies, with a brilliant spray of colorful ink. Take on the role of an Inkling, a squid-like fighter ready to cover yourself and everything around you with your team''s hues. Cover the terrain around you in ink to claim it, and spray walls to gain access to hard-to-reach areas. Earn high-powered super weapons by soaking your turf in ink, so you can cover your enemies in color or spray more territory. Put on your thinking cap to dream up devastating strategies, but do not forget to keep an eye on your turf — too much attention on the other team may lead to a redecoration of your own territory.',
35.00, 44.99, 9, 11, 'splatoon.jpg'),
(NEWID(), 3,
'Yoshis Woolly World', 'On a knitted island filled with many Yarn Yoshis of varying patterns, the evil Magikoopa Kamek turns nearly all the Yoshis into bundles of yarn for his master Baby Bowser, scattering them across different worlds. However, two Yoshis manage to avoid being transformed themselves, and they set off to pursue Kamek and rescue their woolly friends.',
30.00, 49.99, 12, 8, 'yoshi.jpg'),
(NEWID(), 3,
'The Legend of Zelda: The Wind Waker', 'The game is set on a group of islands in a vast sea, a departure for the series. The player controls series protagonist Link as he attempts to save his sister from the sorcerer Ganon and becomes embroiled in a struggle for the Triforce, a sacred relic that grants its holder''s wishes. Aided by allies including pirate captain Tetra and a talking boat named the King of Red Lions, Link sails the ocean, explores islands, and traverses dungeons to acquire the power necessary to defeat Ganon.',
60.00, 79.99, 10, 6, 'windwaker.jpg'),
(NEWID(), 3,
'Mario Party 10', 'Mario Party 10 has tons of fun new ways to play, challenge, and triumph over your friends, with new modes and a wealth of other exciting goodies. Strategize your way around a variety of unique boards to gather coins and stars, and best your buddies. In Bowser Party mode, you can take the role of bad guy Bowser to mess with your friends game. Need to let off some steam? Challenge your friends to a bunch of exciting mini-games, unlock bonus content, and more.',
20.00, 39.99, 9, 11, 'marioparty10.jpg'),
(NEWID(), 3,
'Hyrule Warriors', 'Cut down legions of enemies as Link, Midna, and other Legend of Zelda characters using over-the-top powerful Dynasty-Warriors-style moves. This tour de force through the beloved locales of Hyrule will have you battling the fiercest enemies in Zelda history. Collect materials and rupees to enhance your character, upgrade weapons, and dominate.',
40.00, 59.99, 9, 13, 'hyrulewarriors.jpg'),
(NEWID(), 3,
'Super Mario Maker', 'Design, create and play your own levels on your Wii U GamePad, and then explore those levels created by Nintendo and players from around the world. Use your GamePads touch screen to add enemies, blocks, pipes and more. Combine enemies, traps and items into unexpected twists to break conventions and add unique challenges. Choose from four distinct themes, such as Super Mario Bros., Super Mario Bros. 3, Super Mario World and New Super Mario Bros. U, each with unique art styles and features. Drop in the Mystery Mushroom item to transform into different characters at random, and unlock additional characters by completing 100 Mario Challenge mode or tapping in compatible amiibo figures.',
30.00, 49.99, 12, 7, 'mariomaker.jpg'),
(NEWID(), 3,
'Paper Mario: Color Splash', 'Relax with Wii Us version of the Paper Mario: Color Splash game. Everyones favorite Italian plumber is sent to Prism Island, which has been drained of its color. Mario brings justice to Prism Island in Paper Mario: Color Splash, and he uses the Paint Hammer to restore life as well as color.',
40.00, 59.99, 14, 6, 'papermario.jpg'),
(NEWID(), 3,
'Star Fox Zero', 'Be the hero in Star Fox Zero, the continuation of the legendary Star Fox series. Blast through the enemy forces that are threatening the Lylat system so that you can enjoy peace once more. A variety of tools are at your disposal including the Arwing jet and the Landmaster tank in Star Fox Zero.',
45.00, 62.99, 9, 10, 'starfox.jpg'),
(NEWID(), 4,
'The Legend of Zelda: Breath of the Wild', 'Travel back to Hyrule with Link in Zelda: Breath of the Wild for the Nintendo Switch. Explore a variety of shrines, sail across rough waters and scavenge for food to defeat Ganondorf and save Zelda once and for all. Zelda: Breath of the Wild includes Wolf, who joins Link in his adventure and delivers enhanced gameplay for greater enjoyment.',
40.00, 59.99, 7, 25, 'breathofthewild.jpg'),
(NEWID(), 4,
'Mario Kart 8 Deluxe', 'Battle new enemies on a host of fun tracks with Mario Kart 8 Deluxe for the Nintendo Switch. Three new vehicles and a smart steering feature make this game perfect for both beginners or seasoned pros. In Mario Kart 8 Deluxe you can hold up to two items at a time to attack your enemies.',
40.00, 59.99, 6, 15, 'mariokart8deluxe.jpg'),
(NEWID(), 4,
'Super Mario Odyssey', 'Explore huge 3D kingdoms filled with secrets and surprises, including costumes for Mario and lots of ways to interact with the diverse environments. Cruise in vehicles that incorporate the HD Rumble feature of the Joy-Con controller, or explore sections as Pixel Mario. Thanks to his new friend Cappy, Mario has brand-new moves for you to master, such as cap throw, cap jump, and capture. Visit astonishing new locales, such as the skyscraper-packed New Donk City, and run into familiar friends and foes as you try to save Princess Peach from Bowsers clutches and foil his dastardly wedding plans',
50.00, 69.99, 10, 30, 'supermarioodyssey.jpg'),
(NEWID(), 4,
'Super Bomberman R', 'Dive into a simple yet addictive gameplay by controlling the main character, placing bombs, and battling enemies and rivals. All iconic Bomberman elements return to the game including a dynamite list of items found within the destructible areas of each maze. Take out CPU-controlled adversaries in Story mode to clear a series of 50 unique stages in order to save the galaxy. Players can go head-to-head in heated Battle mode where up to eight players are dropped within a maze until the last man standing is declared the winner. As players gain even more devastating capabilities, they must use all their skills and ingenuity to ensure their opponents get caught in a blast while avoiding its fiery touch',
30.00, 49.99, 7, 20, 'superbomberman.jpg'),
(NEWID(), 4,
'Splatoon 2', 'Play local and online multiplayer, compete in local multiplayer Turf War battles, whether in TV mode or on the go in handheld or tabletop modes. New dual-wielding Splat Dualies join the action, complete with a new Dodge Roll move. Mainstays like the Splat Roller and Splat Charger have also been remixed to include new gameplay mechanics and brand-new special weapons. Play using Joy-Con controllers or the Nintendo Switch Pro Controller, both of which enable gyro controls for better aiming and control',
50.00, 69.99, 10, 25, 'splatoon2.jpg');